dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3.5"
virtualenv:
  system_site_packages: true

  # command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  
matrix:
  allow_failures:
  - rvm: 1.9.3
  include:
  - name: "3.7.3 Production Py"
    python: "3.7.3"
    env: TEST_SUITE=suite_3_5_unit
  - name: "3.5 Integration Tests"
    python: "3.5"
    env: TEST_SUITE=suite_3_5_integration
  - name: "pypy Unit Tests"
    python: "pypy"
    env: TEST_SUITE=suite_pypy_unit
script: ./src/sgapi/__init__.py

branches:
  only:
  - master
  - stable

matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.rails-2.3.x
    env: ISOLATED=true
  - rvm: jruby
    gemfile: gemfiles/Gemfile.rails-2.3.x
    env: ISOLATED=true